version: 0.0
os: linux
files:
  - source: frontend/build
    destination: /var/www/html
  - source: backend
    destination: /var/backend
  - source: configurations/nginx.conf
    destination: /etc/nginx/conf.d/default.conf
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
